import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import Footer from './common/footer';
import styles from './layout.module.scss';
import SearchInput from './SearchInput';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'League App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/matches"> Matches</Link>
          <Link href="/ranked"> Ranks</Link>
        </nav>
        <div className="flex flex-lol gap.10 items-center p-6">
          <div className={styles.searchinput}>
            <SearchInput />
          </div>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
